<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="MoveCommand" Id="{bbcc1778-341b-0460-0c2a-6a236fd3a701}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ABSTRACT MoveCommand EXTENDS Mc2AxisCommand IMPLEMENTS I_MoveCommand
VAR
	_velocity : LREAL;
	_acceleration: LREAL;
	_deceleration: LREAL;
	_jerk: LREAL;
	_bufferMode: AxisBufferMode;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{c3541b45-6c8b-0ebe-3bc3-d96d4d2763e4}">
      <Declaration><![CDATA[PROPERTY PUBLIC ABSTRACT IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{75e50274-88dc-051f-04fb-7f596222b2e8}">
        <Declaration><![CDATA[PUBLIC]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>