<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Mc2MotionCommand" Id="{b9feb950-837c-0c63-3efe-0cf9473a606f}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK INTERNAL ABSTRACT Mc2MotionCommand EXTENDS Mc2Command IMPLEMENTS MotionCommand
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Active" Id="{6e440f34-2bfa-01bb-08ff-9edd6af43fbb}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY PUBLIC ABSTRACT Active : BOOL]]></Declaration>
      <Get Name="Get" Id="{f0c67215-0008-0488-0c4d-4470e62a6019}">
        <Declaration><![CDATA[PUBLIC]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>