<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Mc2MotionCommand" Id="{b9feb950-837c-0c63-3efe-0cf9473a606f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL ABSTRACT Mc2MotionCommand EXTENDS BaseMotionCommand IMPLEMENTS MoveCommand
VAR
	axis_ref : REFERENCE TO Tc2_Mc2.Axis_Ref;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{1d339a18-99d9-03db-3272-4fb59489c4bf}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	axis : REFERENCE TO Mc2Axis;   
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[axis_ref REF= axis.Mc2AxisRef;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>